# Generated by Django 2.0.4 on 2018-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubdata',
            name='victim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
